### ISSUE TITLE
Python label has wrong version number

### ISSUE THREAD

**Issue by DerSchinken** [DerSchinken/BetterString#3]
**Describe the bug**
The Python label on the readme has the wrong version numner

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Readme.md

**Expected behaviour**
Python label is 3.8 instead of 3.6

**Screenshots**
![image](https://user-images.githubusercontent.com/53398996/117566975-0dfca980-b0ba-11eb-9142-87239b9057ca.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Firefox
 - Version: newest

**Comment by DrBumm** [comment]
I don't know how to fix it. Maybe it is an bug with my browser or GitHub

**Comment by DrBumm** [comment]
I tried it with 2 other browsers now and it seems to be a bug from GitHub

**Comment by DrBumm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Python label has wrong version number](https://trello.com/c/lA0OKfPT/19-python-label-has-wrong-version-number)

**Comment by DerSchinken** [comment]
fixed it
